#!/bin/bash

# Update Ubuntu
apt update
apt upgrade -y
apt autoremove -y

# Install required packages
apt install -y \
  openssh-server \
  nginx \
  sqlite3 \
  vim \
  curl \
  git \
  libsqlite3-dev libssl-dev libcurl4-openssl-dev

# Add log directory for Bialet
mkdir -p /var/log/bialet/

# Copy configuration files
cp -R etc/* /etc
cp bin/* /usr/local/bin

# Restart services
systemctl daemon-reload
systemctl enable nginx
systemctl enable bialet-dev.ar
systemctl restart nginx
systemctl restart bialet-dev.ar
